version: 1.2
workflows:
   - name: check_md5
     subclass: WDL
     primaryDescriptorPath: /check_md5.wdl
     testParameterFiles:
         - /check_md5.json
   - name: data_model_report
     subclass: WDL
     primaryDescriptorPath: /data_model_report.wdl
     testParameterFiles:
         - /data_model_report.json
   - name: data_table_import
     subclass: WDL
     primaryDescriptorPath: /data_table_import.wdl
     testParameterFiles:
         - /data_table_import.json
