version: 1.2
workflows:
   - name: check_md5
     subclass: WDL
     primaryDescriptorPath: /check_md5.wdl
     testParameterFiles:
         - /check_md5.json
   - name: data_model_report
     subclass: WDL
     primaryDescriptorPath: /data_model_report.wdl
     testParameterFiles:
         - /data_model_report.json
   - name: data_table_import
     subclass: WDL
     primaryDescriptorPath: /data_table_import.wdl
     testParameterFiles:
         - /data_table_import.json
   - name: data_dictionary_report
     subclass: WDL
     primaryDescriptorPath: /data_dictionary_report.wdl
     testParameterFiles:
         - /data_dictionary_report.json
   - name: validate_data_model
     subclass: WDL
     primaryDescriptorPath: /validate_data_model.wdl
     testParameterFiles:
         - /validate_data_model.json
