name: Womtool

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore: [ "docs/**" ]

  push:
    branches: [ "main" ]
    paths-ignore: [ "docs/**" ]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  run-womtool:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        wdl-file: [
          ./validate_data_model.wdl,
          ./backup_data_tables.wdl,
          ./data_model_report.wdl,
          ./calc_md5.wdl,
          ./check_md5.wdl,
          ./md5_hex.wdl,
          ./data_table_import.wdl,
          ./data_table_export.wdl
        ]

    name: "Run womtool: ${{ matrix.wdl-file }}"

    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Run womtool
        uses: UW-GAC/womtool-action@main
        with:
            wdl-file: ${{ matrix.wdl-file }}
